const endpointsOne = [
    'patients',
    'patient_conditions',
    'patient_conditions_family',
    'patient_panel_status',
    'patient_procedures',
    'patient_respiratordetails',
    'patient_targets',
    'order_question_answers',
    'order_question_index',
    'order_questions',
    'order_requests_revisions',
    'incident_bls',
    'incident_bls_revision',
    'incident_users',
    'incidents',
    'incidents_revision',
    'encounter_billing',
    'encounter_orders',
    'encounter_orders_revisions',
    'encounter_service_types',
    'encounter_users',
    'encounters',
    'encounters_current',
    'panel_chart',
    'panel_membership',
    'panel_membership_doc',
    'panel_membership_resp_chart',
    'panel_restriction',
    'panel_work_region',
    'rx_allergy_custom',
    'rx_nosub',
    'rxlist',
    'rxlist_allergylist',
    'rxlist_drug_instructions',
    'rxlist_instructions',
    'rxlist_term_replace',
    'document_attachments',
    'documents',
    'documents_read',
    'scripted_rule_items',
    'scripted_rules',
    'transactions',
    'user_chart_tabs',
    'user_moveable_layout',
    'v_ledger',
    'v_order_fee_schedule',
    'warnings_restricted',
    'print_queue_multi',
    'print_section_insurance_plans',
    'refer_to_systems_extended_index',
    'refer_to_systems_extended_values',
    'pat_chart_types',
    'pat_pat_relations',
    'incoming_file_queue',
    'insurance_policy',
    'insurance_pre_cert',
    'label_translate',
    'ledger',
    'ledger_links',
    'libraries',
    'measure_enrollment',
    'nature_of_injury_types',
    'oauth_authorization_codes',
    'observations',
    'fee_schedule',
    'fee_schedule_name',
    'fee_schedule_new',
    'ifq_categories',
    'ifq_permissions',
    'ifq_recipient',
    'drug_alias',
    'enc_vt_cpt_picklists',
    'accommodations',
    'apt_type_templates',
    'body_part_types',
    'chart_display_order',
    'cron_ext_options',
    'datasend_route_revisions'
]

const endpointsTwo = [
    'patients',
    'patient_conditions',
    'patient_conditions_family',
    'patient_procedures',
    'patient_targets',
    'incidents',
    'incidents_revision',
    'encounter_orders',
    'encounter_orders_revisions',
    'encounters',
    'encounters_current',
    'rxlist',
    'rxlist_allergylist',
    'documents',
    'print_queue_multi',
    'pat_chart_types',
    'pat_pat_relations',
    'insurance_policy',
    'observations',
    'accommodations'
]

const endpointsThree = [
    'patients',
    'patient_conditions',
    'patient_conditions_family',
    'patient_procedures',
    'patient_targets',
    'incidents',
    'encounter_orders',
    'encounters',
    'encounters_current',
    'rxlist',
    'rxlist_allergylist',
    'insurance_policy',
]

const identifiers = {
    "patients": "pat_id",
    "patient_conditions": "cond_id",
    "patient_conditions_family": "fam_cond_id",
    "patient_panel_status": "pps_id",
    "patient_partitions": "id",
    "patient_partitions_restricted": "id",
    "patient_procedures": "prochrist_id",
    "patient_respiratordetails": "RespRecID",
    "patient_targets": "id",
    "patient_clinical_restrictions": "cr_id",
    "order_items": "item_id",
    "order_items_revisions": "id",
    "order_list": "order_id",
    "order_panels": "id",
    "order_pick_list": "pick_list_id",
    "order_question_answers": "id",
    "order_question_index": "id",
    "order_questions": "ques_id",
    "order_request_icd9cm": "id",
    "order_request_icd9cm_revisions": "id",
    "order_requests": "request_id",
    "order_requests_revisions": "id",
    "order_status_list": "id",
    "order_types": "id",
    "incident_bls": "id",
    "incident_bls_codes": "bls_code",
    "incident_bls_revision": "id",
    "incident_casenum": "id",
    "incident_extended_fields": "id",
    "incident_extended_fields_revision": "id",
    "incident_links": "id",
    "incident_nibp": "nibp_id",
    "incident_users": "iu_id",
    "incidents": "inc_id",
    "incidents_revision": "id",
    "encounter_billing": "bill_id",
    "encounter_exams": "exam_id",
    "encounter_extended_values": "id",
    "encounter_orders": "enc_order_id",
    "encounter_orders_revisions": "id",
    "encounter_service_types": "id",
    "encounter_stages": "stage_id",
    "encounter_templates": "id",
    "encounter_users": "eu_id",
    "encounter_visit_types": "visit_type_id",
    "encounters": "encounter_id",
    "encounters_current": "id",
    "encounters_link": "id",
    "panel": "id",
    "panel_action": "pan_act_id",
    "panel_action_enc_order": "id",
    "panel_action_related": "par_id",
    "panel_chart": "id",
    "panel_membership": "pm_id",
    "panel_membership_doc": "id",
    "panel_membership_resp_chart": "pmrc_id",
    "panel_regulation": "reg_id",
    "panel_restriction": "panel_id",
    "panel_trigger": "pt_id",
    "panel_work_region": "id",
    "rx_allergy_custom": "allergy_id",
    "rx_nosub": "id",
    "rx_commonsigs": "sig_id",
    "rxlist": "rxid",
    "rxlist_allergy_reactions": "id",
    "rxlist_allergylist": "rxagyid",
    "rxlist_commonscripts": "common_rx_id",
    "rxlist_drug_instructions": "id",
    "rxlist_frequencies": "id",
    "rxlist_indications": "indication_id",
    "rxlist_instructions": "instruct_id",
    "rxlist_kit": "kit_id",
    "rxlist_kit_item": "kit_item_id",
    "rxlist_refills": "refill_id",
    "rxlist_term_replace": "id",
    "document_sign": "id",
    "document_attachments": "id",
    "document_types": "doc_type_id",
    "documents": "doc_id",
    "documents_link": "id",
    "documents_read": "docread_id",
    "documents_txt": "id",
    "other": "id",
    "schedules": "script_id",
    "scripted_logic": "rule_item_id",
    "scripted_rule_items": "rule_id",
    "scripted_rule_lookup": "rule_id",
    "scripted_rules": "id",
    "security_role_acl": "security_role_id",
    "security_roles": "report_id",
    "system_reports": "id",
    "tabs": "task_template_id",
    "task_template": "id",
    "task_template_users": "tl_evt_id",
    "tasklist_events": "trx_id",
    "transactions": "id",
    "translate": "id",
    "translate_map": "id",
    "user_chart_tabs": "id",
    "user_moveable_layout": "id",
    "user_roles": "role_id",
    "users": "user_id",
    "v_ledger": "ledger_id",
    "v_order_fee_schedule": "order_id",
    "visit_types_restricted": "id",
    "warnings_restricted": "id",
    "pft": "pft_id",
    "pft_maneuver": "maneuver_id",
    "preferences": "id",
    "print_queue_multi": "queue_id",
    "print_queue_multi_sequence": "append_id",
    "print_section_doctypes": "id",
    "print_section_insurance_plans": "id",
    "print_sections": "id",
    "realms": "id",
    "refer_to_systems": "ext_id",
    "refer_to_systems_extended_index": "id",
    "refer_to_systems_extended_values": "relation_type_id",
    "relation_types": "chart_type_id",
    "pat_chart_types": "pat_rel_id",
    "pat_pat_relations": "fileq_id",
    "incoming_file_queue": "id",
    "injection_codes_mask": "injection_id",
    "injections": "plan_id",
    "insurance_plans": "policy_id",
    "insurance_policy": "cert_id",
    "insurance_pre_cert": "request_id",
    "lab_requests": "tr_id",
    "label_translate": "langsup_id",
    "languages_supported": "lay_id",
    "layout": "id",
    "layout_document_types": "ledger_id",
    "ledger": "ledger_id",
    "ledger_links": "id",
    "libraries": "id",
    "locations": "id",
    "login_trusts": "enrollment_id",
    "measure_enrollment": "id",
    "model": "id",
    "model_security": "id",
    "multi_type_sched": "id",
    "nature_of_injury_types": "na_id",
    "oauth_authorization_codes": "code_id",
    "object_notes": "objnote_id",
    "obs_forms": "obs_item_id",
    "observation_codes": "obs_code",
    "observation_codes_list": "id",
    "observation_flags": "id",
    "observation_ranges": "range_id",
    "observations": "obs_id",
    "observations_snomed": "id",
    "fee_schedule": "id",
    "fee_schedule_name": "profile_id",
    "fee_schedule_new": "fee_id",
    "ifq_categories": "id",
    "ifq_permissions": "ifqp_id",
    "ifq_recipient": "ifqr_id",
    "drug_alias": "drug_alias_id",
    "enc_vt_cpt_picklists": "id",
    "$rxdb$.Measures": "measureId",
    "$rxdb$.rxnconso": "rxnconso_id",
    "abbreviations": "term_id",
    "acceptable_ips": "id",
    "accommodations": "accom_id",
    "action_rule": "action_rule_id",
    "admin_code": "id",
    "appointment_cancel_codes": "id",
    "apt_type_templates": "id",
    "apt_types": "apt_type_id",
    "audio": "audio_id",
    "autocomplete_field": "ac_id",
    "body_part_types": "bod_id",
    "c_scriptlet_data": "sd_id",
    "chart_display_order": "id",
    "chart_type_link": "id",
    "chart_types": "chart_type_id",
    "chartprintdefs": "id",
    "charts": "id",
    "charttab_doctypes": "ctab_id",
    "charttab_relations": "id",
    "charttabs": "type_id",
    "charttabs_restricted": "cl_id",
    "clinical_restriction_types": "id",
    "coding_link": "ceo_id",
    "cron": "route_id",
    "cron_ext_options": "id",
    "datasend_route": "sign_id",
    "datasend_route_revisions": "dep_id",
    "datebegin_esigning": "dep_id"
  };

module.exports = { endpointsOne, endpointsTwo, endpointsThree, identifiers };
