const error = require('../errors');

const identifiers = {
  "patients": "pat_id",
  "patient_conditions": "cond_id",
  "patient_conditions_family": "fam_cond_id",
  "patient_panel_status": "pps_id",
  "patient_partitions": "id",
  "patient_partitions_restricted": "id",
  "patient_procedures": "prochrist_id",
  "patient_respiratordetails": "RespRecID",
  "patient_targets": "id",
  "patient_clinical_restrictions": "cr_id",
  "order_items": "item_id",
  "order_items_revisions": "id",
  "order_list": "order_id",
  "order_panels": "id",
  "order_pick_list": "pick_list_id",
  "order_question_answers": "id",
  "order_question_index": "id",
  "order_questions": "ques_id",
  "order_request_icd9cm": "id",
  "order_request_icd9cm_revisions": "id",
  "order_requests": "request_id",
  "order_requests_revisions": "id",
  "order_status_list": "id",
  "order_types": "id",
  "incident_bls": "id",
  "incident_bls_codes": "bls_code",
  "incident_bls_revision": "id",
  "incident_casenum": "id",
  "incident_extended_fields": "id",
  "incident_extended_fields_revision": "id",
  "incident_links": "id",
  "incident_nibp": "nibp_id",
  "incident_users": "iu_id",
  "incidents": "inc_id",
  "incidents_revision": "id",
  "encounter_billing": "bill_id",
  "encounter_exams": "exam_id",
  "encounter_extended_values": "id",
  "encounter_orders": "enc_order_id",
  "encounter_orders_revisions": "id",
  "encounter_service_types": "id",
  "encounter_stages": "stage_id",
  "encounter_templates": "id",
  "encounter_users": "eu_id",
  "encounter_visit_types": "visit_type_id",
  "encounters": "encounter_id",
  "encounters_current": "id",
  "encounters_link": "id",
  "panel": "id",
  "panel_action": "pan_act_id",
  "panel_action_enc_order": "id",
  "panel_action_related": "par_id",
  "panel_chart": "id",
  "panel_membership": "pm_id",
  "panel_membership_doc": "id",
  "panel_membership_resp_chart": "pmrc_id",
  "panel_regulation": "reg_id",
  "panel_restriction": "panel_id",
  "panel_trigger": "pt_id",
  "panel_work_region": "id",
  "rx_allergy_custom": "allergy_id",
  "rx_nosub": "id",
  "rx_commonsigs": "sig_id",
  "rxlist": "rxid",
  "rxlist_allergy_reactions": "id",
  "rxlist_allergylist": "rxagyid",
  "rxlist_commonscripts": "common_rx_id",
  "rxlist_drug_instructions": "id",
  "rxlist_frequencies": "id",
  "rxlist_indications": "indication_id",
  "rxlist_instructions": "instruct_id",
  "rxlist_kit": "kit_id",
  "rxlist_kit_item": "kit_item_id",
  "rxlist_refills": "refill_id",
  "rxlist_term_replace": "id",
  "document_sign": "id",
  "document_attachments": "id",
  "document_types": "doc_type_id",
  "documents": "doc_id",
  "documents_link": "id",
  "documents_read": "docread_id",
  "documents_txt": "id",
  "other": "id",
  "schedules": "script_id",
  "scripted_logic": "rule_item_id",
  "scripted_rule_items": "rule_id",
  "scripted_rule_lookup": "rule_id",
  "scripted_rules": "id",
  "security_role_acl": "security_role_id",
  "security_roles": "report_id",
  "system_reports": "id",
  "tabs": "task_template_id",
  "task_template": "id",
  "task_template_users": "tl_evt_id",
  "tasklist_events": "trx_id",
  "transactions": "id",
  "translate": "id",
  "translate_map": "id",
  "user_chart_tabs": "id",
  "user_moveable_layout": "id",
  "user_roles": "role_id",
  "users": "user_id",
  "v_ledger": "ledger_id",
  "v_order_fee_schedule": "order_id",
  "visit_types_restricted": "id",
  "warnings_restricted": "id",
  "pft": "pft_id",
  "pft_maneuver": "maneuver_id",
  "preferences": "id",
  "print_queue_multi": "queue_id",
  "print_queue_multi_sequence": "append_id",
  "print_section_doctypes": "id",
  "print_section_insurance_plans": "id",
  "print_sections": "id",
  "realms": "id",
  "refer_to_systems": "ext_id",
  "refer_to_systems_extended_index": "id",
  "refer_to_systems_extended_values": "relation_type_id",
  "relation_types": "chart_type_id",
  "pat_chart_types": "pat_rel_id",
  "pat_pat_relations": "fileq_id",
  "incoming_file_queue": "id",
  "injection_codes_mask": "injection_id",
  "injections": "plan_id",
  "insurance_plans": "policy_id",
  "insurance_policy": "cert_id",
  "insurance_pre_cert": "request_id",
  "lab_requests": "tr_id",
  "label_translate": "langsup_id",
  "languages_supported": "lay_id",
  "layout": "id",
  "layout_document_types": "ledger_id",
  "ledger": "ledger_id",
  "ledger_links": "id",
  "libraries": "id",
  "locations": "id",
  "login_trusts": "enrollment_id",
  "measure_enrollment": "id",
  "model": "id",
  "model_security": "id",
  "multi_type_sched": "id",
  "nature_of_injury_types": "na_id",
  "oauth_authorization_codes": "code_id",
  "object_notes": "objnote_id",
  "obs_forms": "obs_item_id",
  "observation_codes": "obs_code",
  "observation_codes_list": "id",
  "observation_flags": "id",
  "observation_ranges": "range_id",
  "observations": "obs_id",
  "observations_snomed": "id",
  "fee_schedule": "id",
  "fee_schedule_name": "profile_id",
  "fee_schedule_new": "fee_id",
  "ifq_categories": "id",
  "ifq_permissions": "ifqp_id",
  "ifq_recipient": "ifqr_id",
  "drug_alias": "drug_alias_id",
  "enc_vt_cpt_picklists": "id",
  "$rxdb$.Measures": "measureId",
  "$rxdb$.MIPSDeciles": "none",
  "$rxdb$.rxnconso": "rxnconso_id",
  "abbreviations": "term_id",
  "acceptable_ips": "id",
  "accommodations": "accom_id",
  "action_rule": "action_rule_id",
  "admin_code": "id",
  "appointment_cancel_codes": "id",
  "apt_type_templates": "id",
  "apt_types": "apt_type_id",
  "audio": "audio_id",
  "autocomplete_field": "ac_id",
  "body_part_types": "bod_id",
  "c_scriptlet_data": "sd_id",
  "chart_display_order": "id",
  "chart_type_link": "id",
  "chart_types": "chart_type_id",
  "chartprintdefs": "id",
  "charts": "id",
  "charttab_doctypes": "ctab_id",
  "charttab_relations": "id",
  "charttabs": "type_id",
  "charttabs_restricted": "cl_id",
  "clinical_restriction_types": "id",
  "coding_link": "ceo_id",
  "cron": "route_id",
  "cron_ext_options": "id",
  "datasend_route": "sign_id",
  "datasend_route_revisions": "dep_id",
  "datebegin_esigning": "dep_id"
};

function verify_identifier(endpoint, identifier) {

  // try {

  //   const valid_identifier = identifiers[endpoint];
  
  //   //verify
  //   console.log(valid_identifier, Object.keys(identifier)[0]);
  //   if (valid_identifier != Object.keys(identifier)[0]){
  //     console.log("here?");
  //     throw new error.customError(error.ERRORS.INVALID_IDENTIFIER, `You used an incorrect identifier on the \"${endpoint}\" endpoint. Expected \"${identifiers[endpoint]}\" but instead got \"${Object.keys(identifier)[0]}.\"`);
  //   }
  // } catch {
  //   //console.log("here?");
  //   //assumes a user created endpoint that is not in the dictionary
  // }

  if (identifiers[endpoint]){
      
      const valid_identifier = identifiers[endpoint];
      
      //verify
      if (valid_identifier != Object.keys(identifier)[0]){
        throw new error.customError(error.ERRORS.INVALID_IDENTIFIER, `You used an incorrect identifier on the \"${endpoint}\" endpoint. Expected \"${identifiers[endpoint]}\" but instead got \"${Object.keys(identifier)[0]}.\"`);
      }
  
  }
  
}

module.exports = { verify_identifier };